# Generated by Django 4.1.4 on 2023-12-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_opt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opt',
            new_name='userOtp',
        ),
    ]
